spring.application.name=products-command
server.port=8081

#Con esta configuracion le dcimos a spring esta es la funcion que quiero activar como binding
spring.cloud.function.definition=handleCommands
#Estamos enlazando a la funcion que consume a los comandos, es in por que estamos consumiendo
#El valor es el mismo topico de kafka que en el servicio que envia el topico
spring.cloud.stream.bindings.handleCommands-in-0.destination=products.commands
spring.cloud.stream.bindings.handleCommands-in-0.contentType=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092